### ISSUE TITLE
the migration fails in redmine 3.4.4 with an exception

### ISSUE THREAD

**Issue by smoolya17** [jresinas/redmine_inline_edit_issues#1]
Hi jresinas,

I cloned your `redmine_inline_edit_issues ` plugin to the `plugins` folder 

but i get this error

```
Redmine::PluginNotFound: Redmine::PluginNotFound
C:/Bitnami/redmine-3.4.4-1/apps/redmine/htdocs/lib/redmine/plugin.rb:123:in `fin
d'
C:/Bitnami/redmine-3.4.4-1/apps/redmine/htdocs/lib/redmine/plugin.rb:251:in `req
uires_redmine_plugin'
C:/Bitnami/redmine-3.4.4-1/apps/redmine/htdocs/plugins/redmine_inline_edit_issue
s/init.rb:14:in `block in <top (required)>'
```

**Comment by jresinas** [comment]
Hi @smoolya17,

I think the problem may be that you need the [redmine_base_deface](https://github.com/jbbarth/redmine_base_deface) plugin as requirement to use this one.

I hope it works for you
